[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
groq = "^0.30.0"
streamlit = "^1.46.0"
python-dotenv = "^1.0.0"
toml = "^0.10.2"
pillow = "^11.0.0"
playwright = "^1.51.0"